# .github/workflows/android.yml
# GitHub Actions documentation
# => https://docs.github.com/en/actions
name: android

# Controls when the action will run. Triggers the workflows on push or pull request
# events but only for the master branch
on: [ push, pull_request ]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 8

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test