# .github/workflows/android.yml
# GitHub Actions documentation
# => https://docs.github.com/en/actions
name: android

# Controls when the action will run. Triggers the workflows on push or pull request
# events but only for the master branch
on: [ push, pull_request ]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test