# .github/workflows/runTests.yml
# GitHub Actions documentation
# => https://docs.github.com/en/actions
name: runTests

# Controls when the action will run. Triggers the workflows on push or pull request
# events but only for the master branch
on: [ push, pull_request ]
jobs:
  gradle:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          script: ./gradlew connectedCheck --stacktrace